### ISSUE TITLE
App (possibly) won't run cause of unreachable code on expired subscription 

### ISSUE THREAD

**Issue by HomiG** [polyglot-microfrontends/shared-dependencies#4]
On index.ejs 
there is this line 
`<script type="systemjs-importmap" src="https://storage.googleapis.com/polyglot.microfrontends.app/importmap.json"></script>`
but apparently this google account subscription is expired and it can't download the importmaps.

Maybe this file should be shared from somewhere else?

**_EDIT_** 

Found the solution just change the import source map  - `importmaps.json` - with something that actually servers the libraries

here is my example: 
``` JSON
{
  "imports": {
    "single-spa": "https://cdn.jsdelivr.net/npm/single-spa@5.9.0/lib/system/single-spa.min.js",
    "react": "https://cdn.jsdelivr.net/npm/react@17.0.1/umd/react.production.min.js",
    "react-dom": "https://cdn.jsdelivr.net/npm/react-dom@17.0.1/umd/react-dom.production.min.js",
    "vue": "https://cdn.jsdelivr.net/npm/vue@2.6.12/dist/vue.min.js",
    "vue-router": "https://cdn.jsdelivr.net/npm/vue-router@3.4.9/dist/vue-router.min.js",
    "single-spa-angularjs": "https://cdn.jsdelivr.net/npm/single-spa-angularjs@4.1.0/lib/single-spa-angularjs.js"
  }
}
```

and you can just serve this file `importmaps.json` locally (npm i -g ssl-serve)
```
ssl-serve --cors --ssl
```

**Comment by internettrans** [comment]
The GCP account for that storage bucket has been re-enabled
